### ISSUE TITLE
Feature Request: Limit Pages to Get

### ISSUE THREAD

**Issue by draoZA** [f2calv/CasCap.Apis.GooglePhotos#7]
Hi, would be great to add optional parameter MaxPages to GetMediaItemsAsync. So get stops requesting after defined number of pages. The same could be reached by using the cancel token. But Cancel token would be for "surprising" user cancellation while max pages would be for deterministic stop.

Use case would be if you pull the whole MediaList you might get thousands of pages a) this can take very long and b) if you want to show them until pictures are downloaded download link has expired.

You are already tracking page numbers. So just add it to condition a la
var pageNumber = 1;
  while (pageToken is object && !cancellationToken.IsCancellationRequested && maxPageNumber <= pageNumber)

**Comment by f2calv** [comment]
Sure, added in although with pageNumber <= maxPageNumber. New package should be ready for consumption now...

In reality, due to the position that I placed the new argument in this was a breaking change that should require a semver minor version hike. But I forgot before I pushed the commit ...so the tens of thousands of users of my package will have to just deal with the fallout!

**Comment by draoZA** [comment]
Thanks :-)
